### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by JasonAnn** [inisis/machine-learning-facial-deformer#2]
Hello, thanks for the nice work. I found that the data type of csv list generated by the "generate_csv.py"  is '.npy', however,  my data exported from "generate_frame.py" is '.obj'.  Is there any other step that transforms the obj to npy?

**Comment by inisis** [comment]
Hi, if you use the script that I provided, it should be npy, I think suffix doesn't matter, as long as the needed data is stored.

**Comment by JasonAnn** [comment]
Thaks a lot ! By the way,  there is a step to compure the pca of the dataset and generate two files named 'mean.npy' and 'featVec.npy'.  But I haven't found where these two files are used in the training process ?

**Comment by inisis** [comment]
Hi, these files are used initially to initialize the last fully connected layer, but after ablation study, it's removed since not necessary.

**Comment by JasonAnn** [comment]
> Hi, these files are used initially to initialize the last fully connected layer, but after ablation study, it's removed since not necessary.
Understood, thank you for your response again.
